name: deploy

on:
  push:
    branches:
      - master

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        env:
          TARGET_DIR: /home/${{ secrets.SSH_USERNAME }}
          VENV_BIN: venv/bin
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: 22
          connect_timeout: 10s
          first_ssh: |-
            mkdir -p app
            mkdir -p logs
            test -d venv || python3.9 -m venv venv
            touch .env

          scp: |-
            './app/*' => $TARGET_DIR/app/
            ./poetry.lock => $TARGET_DIR
            ./pyproject.toml => $TARGET_DIR

          last_ssh: |-
            source $VENV_BIN/activate 
            pip install --no-cache-dir poetry pip setuptools
            poetry install --only main
            pip cache purge
            echo 'telegram_token=${{ secrets.TELEGRAM_PROD_TOKEN }}' > .env
            supervisorctl restart stonks:*
